# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Fails if there are any ">>>>>" lines in files due to merge conflicts.
      - id: check-merge-conflict
      # Trims trailing whitespace. Allow a single space on the end of .md lines for hard line breaks.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Makes sure files end in a newline and only a newline;
      - id: end-of-file-fixer
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax; unsafe: only check syntax, do not load yaml
      - id: check-yaml
        args: ["--unsafe"]
      # Check for symlinks that do not point to anything.
      - id: check-symlinks
      # Fail if staged files are above a certain size.
      # To add a large file, use 'git lfs track <file>; git add <file> to track large files with
      # git-lfs rather than commiting them directly to the git history
      - id: check-added-large-files
        args: ["--maxkb=500"]

        # HALT! Before you exclude a large file and commit it, forever
        # bloating our repo size, did you:
        # (1) use a CLI tool like imageoptim to compress them if they are images
        # (2) think hard about whether using DVC or git-lfs is more appropriate
        #     for the file--such as in the case of CSV files or other data
        # This can be confusing. Reach out for help in our chat to help decide
        # how to deal adding these large files you have :)
        exclude: |
          (?x)(
              ^example/large/file.csv|
              ^example/large/sklearn-model.pkl
          )
      # Sort requirements in requirements.txt files.
      - id: requirements-txt-fixer
      # Prevent addition of new git submodules.
      - id: forbid-new-submodules
      # Prevent committing directly to trunk (since Bitbucket wants us to pay for this feature)
      - id: no-commit-to-branch
        args: ["--branch=main"]
      # Detects the presence of private keys
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.261"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --config=./pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.2.0"
    hooks:
      - id: mypy
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --config-file=./pyproject.toml,
          ]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --config=./pyproject.toml

  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.3
    hooks:
      - id: pylint
        args:
          - --rcfile=./pyproject.toml

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --toml-config=./pyproject.toml
        additional_dependencies:
          - radon
          - flake8-docstrings
          - Flake8-pyproject

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --settings-path=./pyproject.toml

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variable
          - --ignore-init-module-imports





#pre-commit hooks in Git, these are scripts that run automatically before a commit is finalized. They allow you to automate tasks
# such as formatting code, running tests, or checking for issues before the changes are committed to the repository.


# Pre-commit hooks are scripts that automatically run before a commit is finalized.
# These hooks are helpful for automating tasks like code formatting, running tests, or checking for issues before the changes are committed to the repository.

# To use pre-commit hooks, follow these steps:

# 1. Install the pre-commit framework.
# Pre-commit helps manage and maintain multi-language hooks. To install it, use the following command:
# pip install pre-commit

# 2. Create a `.pre-commit-config.yaml` file in the root of your project.
# This file defines which hooks will be used. Example configuration:
# 
# .pre-commit-config.yaml:
# - repo: https://github.com/pre-commit/mirrors-autopep8
#   rev: v1.5.6  # Specify the version of the hook
#   hooks:
#     - id: autopep8  # Auto format Python code according to PEP 8

# - repo: https://github.com/pre-commit/mirrors-eslint
#   rev: v2.0.0
#   hooks:
#     - id: eslint
#       name: Run ESLint on JavaScript files

# 3. Install the hooks in your Git repository.
# Run the following command to install the hooks:
# pre-commit install

# 4. (Optional) Manually run the hooks.
# You can manually run the hooks to test them using:
# pre-commit run --all-files

# 5. Example Workflow:
# - After making changes to the code, when you attempt to commit with `git commit`, the pre-commit hook will run automatically before completing the commit.
# - If the hook finds issues (e.g., formatting problems), it will either fix them or warn you, and you will need to address them before proceeding with the commit.
# - If everything is fine, your commit will be finalized.

# Example: Using pre-commit with `.gitignore`:
# If you want to check that your `.gitignore` file is correct before committing, you can add a hook like this:
# 
# - repo: https://github.com/pre-commit/mirrors-gitignore
#   rev: v1.0.0
#   hooks:
#     - id: check-ignore
#       name: Check if .gitignore is valid

# Benefits of using pre-commit hooks:
# - Ensures consistency by enforcing rules like code style and tests across all commits.
# - Automates repetitive tasks such as running a linter or formatting code.
# - Prevents errors by catching issues before they are committed to the repository.
